#!/usr/bin/env python3
"""big_data.py -- Leveling Gears data pipeline entry point.

Downloads cmangos tbc-db's current loot/quest/vendor/recipe SQL dump, confirms its real table/column
structure, and reports findings -- the scaffold DATA_PIPELINE.md called for before any real extraction
parser gets written against guessed schema names. Questie is intentionally NOT included yet: its
source license is unresolved (see DATA_PIPELINE.md) and that's being resolved separately.

Usage:
    python3 big_data.py [--skip-download] [--verbose]

Everything printed to the console is also written to a timestamped file under pipeline/logs/, so a
run can be reviewed later without having kept the terminal scrollback.
"""

import argparse
import logging
import sys
from datetime import datetime
from pathlib import Path

import build_database
import dependencies
import download
import extract_recipes
import inspect_schema
import lua_writer

PIPELINE_DIR = Path(__file__).resolve().parent
DOWNLOADS_DIR = PIPELINE_DIR / "downloads"
OUTPUT_DIR = PIPELINE_DIR / "output"
LOGS_DIR = PIPELINE_DIR / "logs"


def setup_logging(verbose: bool) -> Path:
    LOGS_DIR.mkdir(parents=True, exist_ok=True)
    log_path = LOGS_DIR / f"big_data_{datetime.now():%Y%m%d_%H%M%S}.log"

    root = logging.getLogger()
    root.setLevel(logging.DEBUG if verbose else logging.INFO)
    formatter = logging.Formatter("%(asctime)s [%(levelname)s] %(name)s: %(message)s", "%H:%M:%S")

    console_handler = logging.StreamHandler(sys.stdout)
    console_handler.setFormatter(formatter)
    root.addHandler(console_handler)

    file_handler = logging.FileHandler(log_path, encoding="utf-8")
    file_handler.setFormatter(formatter)
    root.addHandler(file_handler)

    return log_path


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument(
        "--skip-download",
        action="store_true",
        help="Reuse the already-downloaded .sql.gz in pipeline/downloads/ instead of fetching it again",
    )
    parser.add_argument("--verbose", action="store_true", help="Enable DEBUG-level logging")
    parser.add_argument(
        "--extract-recipes",
        action="store_true",
        help="Also run just the recipe extractor and write pipeline/output/Recipes.lua (superseded "
        "by --build-database, kept for quick iteration on the recipe extractor alone)",
    )
    parser.add_argument(
        "--build-database",
        action="store_true",
        help="Run every extractor (Items/Sources/Quests/Chains/Recipes) and write the full "
        "pipeline/output/*.lua set, plus BySlot's index",
    )
    args = parser.parse_args()

    log_path = setup_logging(args.verbose)
    log = logging.getLogger("big_data")
    log.info("Logging to %s", log_path)

    log.info("=== Step 1: dependency check ===")
    if not dependencies.run_all():
        log.error("One or more dependencies are missing -- see instructions above. Stopping.")
        return 1

    log.info("=== Step 2: download cmangos tbc-db ===")
    try:
        sql_path = download.fetch_cmangos_sql(DOWNLOADS_DIR, skip_download=args.skip_download)
    except Exception:
        log.exception("Download/decompress step failed")
        return 1

    log.info("=== Step 3: confirm real schema ===")
    tables = inspect_schema.scan_sql_file(sql_path)
    report_path = OUTPUT_DIR / "schema_report.txt"
    inspect_schema.write_report(tables, report_path)

    if args.build_database:
        log.info("=== Step 4: build the full database (Items/Sources/Quests/Chains/Recipes/BySlot) ===")
        try:
            build_database.build_all(sql_path, OUTPUT_DIR)
        except Exception:
            log.exception("build_database failed")
            return 1
    elif args.extract_recipes:
        log.info("=== Step 4: extract Recipes only ===")
        recipes = extract_recipes.build_recipes(sql_path)
        recipes_path = OUTPUT_DIR / "Recipes.lua"
        lua_writer.write_lua_table(
            "LevelingGearsData_Recipes",
            recipes,
            recipes_path,
            header_comment=(
                "Generated by pipeline/big_data.py --extract-recipes. Not wired into the addon yet --\n"
                "staging output only, see DATA_PIPELINE.md."
            ),
        )
        log.info("Wrote %d recipes to %s", len(recipes), recipes_path)

    log.info("Done. Review %s before writing the next extraction parser.", report_path)
    return 0


if __name__ == "__main__":
    sys.exit(main())
