"""pipeline/build_database.py -- merges every extractor's output into ROADMAP.md's full schema
(Items/Sources/Quests/Chains/Recipes/BySlot) and writes it all to pipeline/output/*.lua.

This is the "draw the outline" pass: real data from every table cmangos actually ships, with known,
explicitly-flagged gaps (spell reagent data, human-readable zone names) left for later sources
rather than guessed at. See DATA_PIPELINE.md's Status note for what's real vs. still a gap.
"""

import logging
from pathlib import Path

import extract_items
import extract_loot
import extract_quests
import extract_recipes
import extract_vendor
import inspect_schema
import lua_writer

log = logging.getLogger("big_data.build_database")

GENERATED_HEADER = (
    "Generated by pipeline/big_data.py --build-database. Not wired into the addon yet -- staging\n"
    "output only, see DATA_PIPELINE.md for what's real vs. a known gap in this pass."
)


def _merge_sources(*source_dicts):
    merged = {}
    for source_dict in source_dicts:
        for item_id, entries in source_dict.items():
            merged.setdefault(item_id, []).extend(entries)
    return merged


def _build_by_slot(items: dict, sources: dict) -> dict:
    """Only items with at least one known way to obtain them are useful to suggest -- an item with
    no Sources entry yet (a real gap in this pass, not every equippable item in the game) is left
    out of BySlot rather than offered with no way to actually get it."""
    by_slot = {}
    for item_id, item in items.items():
        if item_id not in sources:
            continue
        by_slot.setdefault(item["slot"], []).append(item_id)
    return by_slot


def build_all(sql_path: Path, output_dir: Path) -> dict:
    log.info("Confirming real column order once for every table every extractor needs...")
    tables = inspect_schema.scan_sql_file(sql_path)

    log.info("--- Items ---")
    items = extract_items.build_items(sql_path, tables)

    log.info("--- Sources: drop ---")
    loot_sources = extract_loot.build_loot_sources(sql_path, tables)

    log.info("--- Sources: vendor ---")
    vendor_sources = extract_vendor.build_vendor_sources(sql_path, tables)

    log.info("--- Quests, Chains, Sources: quest ---")
    quests, chains, quest_sources = extract_quests.build_quests(sql_path, tables)

    log.info("--- Recipes ---")
    recipes = extract_recipes.build_recipes(sql_path, tables)

    sources = _merge_sources(loot_sources, vendor_sources, quest_sources)
    by_slot = _build_by_slot(items, sources)

    log.info(
        "Merged: %d items, %d items with >=1 source, %d quests, %d chains, %d recipes, "
        "%d slots populated in BySlot",
        len(items), len(sources), len(quests), len(chains), len(recipes), len(by_slot),
    )

    tables_to_write = {
        "Items.lua": ("LevelingGearsData_Items", items),
        "Sources.lua": ("LevelingGearsData_Sources", sources),
        "Quests.lua": ("LevelingGearsData_Quests", quests),
        "Chains.lua": ("LevelingGearsData_Chains", chains),
        "Recipes.lua": ("LevelingGearsData_Recipes", recipes),
        "BySlot.lua": ("LevelingGearsData_BySlot", by_slot),
    }
    for filename, (variable_name, data) in tables_to_write.items():
        path = output_dir / filename
        lua_writer.write_lua_table(variable_name, data, path, header_comment=GENERATED_HEADER)
        log.info("Wrote %s (%d top-level entries)", path, len(data))

    return {
        "items": len(items),
        "sources": len(sources),
        "quests": len(quests),
        "chains": len(chains),
        "recipes": len(recipes),
        "by_slot": len(by_slot),
    }
